export const PATH_PREFIX = '/api/v1';

export enum ENDPOINTS {
  HEALTH = '/health',
  AUTH_REGISTER = '/auth/register',
  AUTH_LOGIN = '/auth/login',
  USERS = '/users',
  USERS_ID = '/users/:id',
  CATEGORIES = '/categories',
  CATEGORIES_ID = '/categories/:id',
  PACKAGES = '/packages',
  PACKAGES_ID = '/packages/:id',
  PRODUCTS = '/products',
  PRODUCTS_ID = '/products/:id',
  DISCOUNTS = '/discounts',
  DISCOUNTS_ID = '/discounts/:id',
  DISCOUNTS_BY_NAME = '/discounts/name/:name',
  ORDERS = '/orders',
  ORDERS_ID = '/orders/:id',
  ORDERS_USER = '/orders-user',
  ORDERS_USER_ID = '/orders-user/:id',
  SEED = '/seed',
  PRODUCTS_FAVORITE = '/products-favorite',
  PRODUCTS_BEST_SELLERS = '/products-best-sellers',
  CATEGORIES_BEST_SELLERS = '/categories-best-sellers',
  USERS_PROFILE = '/users-profile',
  NOTIFICATIONS = '/notifications',
  NOTIFICATIONS_ID = '/notifications/:id',
  NOTIFICATIONS_USERS = '/notifications-users',
}
